language: node_js
install: yarn
script: yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  fqdn: tools.less.run
  project-name: dev-tool
  on:
    branch: master