version: 2.0
jobs:
  build:
    branches:
      ignore: gh-pages
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Yarn Install
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: yarn run build
      - run:
          name: Deploy github pages
          command: |
            mkdir publish
            git clone https://hitian:$GITHUB_TOKEN@github.com/hitian/dev-tools.git --branch gh-pages publish
            pushd publish
            rm -rf ./*
            cp -r ../dist/* .
            echo 'tools.less.run' > CNAME
            git add --all
            git config user.email "ci-bot@hitian.info"
            git config user.name "ci-bot"
            git commit -m "ci build."
            [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ] && git push origin gh-pages
