version: 2.0
jobs:
  build:
    branches:
      ignore: gh-pages
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: build
          environment:
            NODE_OPTIONS: --openssl-legacy-provider
          command: yarn run generate
      - add_ssh_keys:
          fingerprints:
            - "95:53:8a:09:7f:4c:3c:e8:12:74:3c:15:36:ab:af:c4"
      - run:
          name: Deploy github pages
          command: |
            mkdir publish
            git clone git@github.com:hitian/dev-tools.git --branch gh-pages publish
            pushd publish
            rm -rf ./*
            cp -r ../dist/* .
            echo 'tools.less.run' > CNAME
            git add --all
            if [ -z "$(git diff --cached --name-only)" ]; then 
              # Working directory clean
              echo "no change, end."
            else 
              # Uncommitted changes
              git config user.email "ci-bot@hitian.info"
              git config user.name "ci-bot"
              git commit -m "ci build. [ci skip]"
              git push origin gh-pages
              echo "update ok."
            fi
            
