version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Yarn Install
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: yarn run build
      - run:
          name: Deploy Setup
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-bot@circleci.org"
            git config user.name "circleci-bot"
      - run:
          name: Deploy
          command: gh-pages --dist dist
